name: Update Dashboard Data
on:
  schedule:
    - cron: '30 16 * * *' # Runs every hour
  workflow_dispatch: # Allows you to click a button to run it manually
  
permissions:
  contents: write
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run Fetch Script
        run: node script/fetch_data.js
        env:
          MY_GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }} # Pulls from your vault
      - name: Save file to repo
        run: |
          git config --global user.name "Nitish36"
          git config --global user.email "1rn19cs092.nitish.pkv@gmail.com"
          git add github-data.json
          git commit -m "Updated data" || exit 0
          git push
