name: Update Dashboard Data
on:
  schedule:
    - cron: '0 * * * *' # Runs every hour
  workflow_dispatch: # Allows you to click a button to run it manually

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run Fetch Script
        run: node scripts/fetch_data.js
        env:
          MY_GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }} # Pulls from your vault
      - name: Save file to repo
        run: |
          git config --global user.name "Robot"
          git config --global user.email "robot@github.com"
          git add github-data.json
          git commit -m "Updated data" || exit 0
          git push
